ccc
%% PLOT CARS 
ccc
% FOLLOWINGS ARE NEEDED TO RUN ONCE
rszwh  = [100 200];
carwh  = [4.5 1.8];
% POSITIONS
rcarpos = [1 2 210];
gcarpos = [4 2 90];
bcarpos = [3 9 30];
pcarpos = [9 3 300];
% LOAD IMAGES
[rcarimg, ~, rcartr] = imread('imgs/redcar.png');
rcarrsz = imresize(rcarimg, rszwh);
rtrrsz  = imresize(rcartr, rszwh);
[gcarimg, ~, gcartr] = imread('imgs/greencar.png');
gcarrsz = imresize(gcarimg, rszwh);
gtrrsz  = imresize(gcartr, rszwh);
[bcarimg, ~, bcartr] = imread('imgs/bluecar.png');
bcarrsz = imresize(bcarimg, rszwh);
btrrsz  = imresize(bcartr, rszwh);
[pcarimg, ~, pcartr] = imread('imgs/purplecar.png');
pcarrsz = imresize(pcarimg, rszwh);
ptrrsz  = imresize(pcartr, rszwh);

% THIS HAS TO RUN EVERY TIME. 
% PLOT
figure(); hold on;
set(gcf,'Color', [0.6, 0.9, 0.8]/4 );
[xmesh_grid, ymesh_grid] = get_carmeshgred(rcarpos, carwh, rszwh);
h = surf('xdata', xmesh_grid, 'ydata', ymesh_grid ...
    , 'zdata', zeros(rszwh(1), rszwh(2)) ...
    , 'cdata', rcarrsz, 'AlphaData', rtrrsz ...
    , 'FaceAlpha', 'texture' ...
    , 'FaceColor', 'texturemap' ...
    , 'EdgeColor','None', 'LineStyle', 'None');
[xmesh_grid, ymesh_grid] = get_carmeshgred(gcarpos, carwh, rszwh);
h = surf('xdata', xmesh_grid, 'ydata', ymesh_grid ...
    , 'zdata', zeros(rszwh(1), rszwh(2)) ...
    , 'cdata', gcarrsz, 'AlphaData', gtrrsz ...
    , 'FaceAlpha', 'texture' ...
    , 'FaceColor', 'texturemap' ...
    , 'EdgeColor','None', 'LineStyle', 'None');
[xmesh_grid, ymesh_grid] = get_carmeshgred(bcarpos, carwh, rszwh);
h = surf('xdata', xmesh_grid, 'ydata', ymesh_grid ...
    , 'zdata', zeros(rszwh(1), rszwh(2)) ...
    , 'cdata', bcarrsz, 'AlphaData', btrrsz ...
    , 'FaceAlpha', 'texture' ...
    , 'FaceColor', 'texturemap' ...
    , 'EdgeColor','None', 'LineStyle', 'None');
[xmesh_grid, ymesh_grid] = get_carmeshgred(pcarpos, carwh, rszwh);
h = surf('xdata', xmesh_grid, 'ydata', ymesh_grid ...
    , 'zdata', zeros(rszwh(1), rszwh(2)) ...
    , 'cdata', pcarrsz, 'AlphaData', ptrrsz ...
    , 'FaceAlpha', 'texture' ...
    , 'FaceColor', 'texturemap' ...
    , 'EdgeColor','None', 'LineStyle', 'None');
axis equal off; grid on; 
xlabel('X'); ylabel('Y');
title('Plot Cars', 'FontSize', 15, 'Color', 'w');

%%
